version: "3"
services:
  mysql:
    image: mysql:latest
    build:
      context: ./mysql
    environment:
      MYSQL_DB_CONNECTION: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3307:3306"
    networks:
      - test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
    networks:
      - test
  webserver:
    build: .
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - test

networks:
  test:
    driver: bridge
